#!/bin/sh

# Update SVN repo
svn up

# Add all new and modified files.
git add .

# Remove files deleted by SVN.
git rm $(git ls-files --deleted)

# Retrieve SVN revision for commit message
svnrev=`svn info | awk '/Revision:/ { print $2 }'`

# Commit !
git commit -m "SVN Update, revision $svnrev"
